### ISSUE TITLE
Launch NAO Core agent error

### ISSUE THREAD

**Issue by klpanagi** [rapp-project/rapp-robot-nao#16]
Following the [Wiki documentation](https://github.com/rapp-project/rapp-robot-nao/wiki/Running-core-agent#running-rapp_core_agent), launching the NaoCoreAgent by executing:

```bash
$ bash /home/nao/scripts/nao_launch_core_agent.sh
```

procuces the following error:

```bash
Traceback (most recent call last):
  File "/home/nao/ws_ros_additional_packages/install_isolated/bin/roslaunch", line 34, in <module>
    import roslaunch
  File "/home/nao/ws_ros_additional_packages/install_isolated/lib/python2.7/site-packages/roslaunch/__init__.py", line 56, in <module>
    from .launch import ROSLaunchRunner
  File "/home/nao/ws_ros_additional_packages/install_isolated/lib/python2.7/site-packages/roslaunch/launch.py", line 55, in <module>
    from roslaunch.nodeprocess import create_master_process, create_node_process
  File "/home/nao/ws_ros_additional_packages/install_isolated/lib/python2.7/site-packages/roslaunch/nodeprocess.py", line 52, in <module>
    from rosmaster.master_api import NUM_WORKERS
  File "/home/nao/ws_ros_additional_packages/install_isolated/lib/python2.7/site-packages/rosmaster/__init__.py", line 35, in <module>
    from .main import rosmaster_main
  File "/home/nao/ws_ros_additional_packages/install_isolated/lib/python2.7/site-packages/rosmaster/main.py", line 43, in <module>
    import rosmaster.master
  File "/home/nao/ws_ros_additional_packages/install_isolated/lib/python2.7/site-packages/rosmaster/master.py", line 47, in <module>
    import rosmaster.master_api
  File "/home/nao/ws_ros_additional_packages/install_isolated/lib/python2.7/site-packages/rosmaster/master_api.py", line 72, in <module>
    from rosmaster.util import xmlrpcapi
  File "/home/nao/ws_ros_additional_packages/install_isolated/lib/python2.7/site-packages/rosmaster/util.py", line 48, in <module>
    from defusedxml.xmlrpc import monkey_patch
ImportError: No module named defusedxml.xmlrpc
```

**EDIT**:

Question: Is the Wiki documentation up-to-date?
Question: Where are the NaoCoreAgent Services documented?

**Comment by etsardou** [comment]
@dudekw about these two questions?

Question: Is the Wiki documentation up-to-date? (the wiki says about HOP Hz - is this the way applications are fetched?)

Question: Where are the NaoCoreAgent Services documented? (once we start the core agent we can give keywords and download applications from the store?)

**Comment by dudekw** [comment]
Thank you for your reports. The bug was in one of the compilation scripts. 

The following steps should fix the error:
1) `cd ~/ws_ros_additional_packages/src/ros_comm`
2) `git checkout indigo-devel`
3) `source ~/ws_ros/install_isolated/setub.bash`
4) `catkin_make_isolated --install -DCMAKE_BUILD_TYPE=Release -DCMAKE_MODULE_PATH=/home/nao/ws_ros_additional_packages/programs/eigen-eigen-bdd17ee3b1b3/cmake -DCMAKE_CC_COMPILER=/usr/bin/cc -DCMAKE_CXX_COMPILER=/usr/bin/c++ `

**Comment by dudekw** [comment]
@etsardou 

1) Yes it should be updated, we will take care about it. @mfigat 
2) @maciek-slon should know the answer to that question.

**Comment by maciek-slon** [comment]
I've added short description of voice comunication: https://github.com/rapp-project/rapp-robot-nao/wiki/Running-core-agent
